### ISSUE TITLE
Leader Change Hook

### ISSUE THREAD

**Issue by fredfortier** [datafuse-extras/async-raft#11]
What's the best way to hook into leader change events? I see how it's done internally, each `append_entry` request has this guard:
```rust
     if self.current_leader.as_ref() != Some(&msg.leader_id) {
         self.update_current_leader(UpdateCurrentLeader::OtherNode(msg.leader_id));
         report_metrics = true;
     }
```
But this `leader_id` field is dropped by the time by time my impl is called:
```rust
    #[tracing::instrument(level = "trace", skip_all, fields(len=%entries.len()))]
    async fn append_to_log(&self, entries: &[&Entry<SequencedRequest>]) -> Result<()> {
        // What's the cheapest way to find out whether this entry has a new leader?
        todo!()
    }
 ```
Basically, I need set some context following a leader re-election BEFORE applying the associated entry to the state machine? I could simply query the `RaftMetrics` in `apply_to_state_machine` if that's how the control flow works. As it stands, I'm not 100% sure when `report_metrics` takes effect because it sends the update asynchronously:
```rust
        let res = self.tx_metrics.send(RaftMetrics {
            id: self.id,
            state: self.target_state,
            current_term: self.current_term,
            last_log_index: self.last_log_id.index,
            last_applied: self.last_applied.index,
            current_leader: self.current_leader,
            membership_config: self.membership.clone(),
            snapshot: self.snapshot_last_log_id,
            leader_metrics,
        });
```

**Comment by drmingdrmer** [comment]
AFAIK, `send()` is synchronized between threads. E.g. a `Receiver::borrow()` that is called after `send()` should always see the updated value:
https://docs.rs/tokio/1.8.0/src/tokio/sync/watch.rs.html#360
https://docs.rs/tokio/1.8.0/src/tokio/sync/watch.rs.html#231

But you are still not guaranteed to see the correct `leader` because the leader may have changed again.

What's your root need for this? Why do you need the leader-id when applying a log entry? 🤔 
Since there is no guarantee that every follower sees the same leader-id when applying a certain log entry.
